LineBot_Order_Core_Web/Controllers/AuthorizeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Security.Cryptography;
using System.Threading.Tasks;
using LineBot_Order_Core_Web.Extensions;
using LineBot_Order_Core_Web.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.WebUtilities;
using Microsoft.Extensions.Logging;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace LineBot_Order_Core_Web.Controllers
{
    [Route("[controller]")]
    public class AuthorizeController : Controller
    {
        private readonly LineNotifyConfig _lineNotifyConfig;
        readonly ILogger<AuthorizeController> _log;        
        
        public AuthorizeController(ILogger<AuthorizeController> log, LineNotifyConfig lineNotifyConfig)
        {
            _log = log;
            _lineNotifyConfig = lineNotifyConfig;
        }

        // GET: api/Authorize
        /// <summary>設定與 Lind Notify 連動</summary>
        [HttpGet]
        public IActionResult GetAuthorize()
        {            
            var uri = Uri.EscapeUriString(
                _lineNotifyConfig.AuthorizeUrl + "?" +
                "response_type=code" +
                "&client_id=" + _lineNotifyConfig.ClientId +
                "&redirect_uri=" + _lineNotifyConfig.CallbackUrl +
                "&scope=notify" +
                "&state=" + _lineNotifyConfig.State
            );
            Response?.Redirect(uri);

            return new EmptyResult();
        }

        // GET: api/Authorize/Callback 綁給 Line Notify
        /// <summary>取得使用者 code</summary>
        /// <param name="code">用來取得 Access Tokens 的 Authorize Code</param>
        /// <param name="state">驗證用。避免 CSRF 攻擊</param>
        /// <param name="error">錯誤訊息</param>
        /// <param name="errorDescription">錯誤描述</param>
        /// <returns></returns>
        [HttpGet]
        [Route("Callback")]
        public async Task<IActionResult> GetCallback(
            [FromQuery] string code,
            [FromQuery] string state,
            [FromQuery] string error,
            [FromQuery][JsonProperty("error_description")] string errorDescription)
        {
            if (!string.IsNullOrEmpty(error))
                return new JsonResult(new
                {
                    error,
                    state,
                    errorDescription
                });

            Response.Redirect(_lineNotifyConfig.SuccessUrl + "?token=" + await FetchToken(code));

            return new EmptyResult();
        }

        /// <summary>取得使用者 Token</summary>
        /// <param name="code">用來取得 Access Tokens 的 Authorize Code</param>
        /// <returns></returns>
        private async Task<string> FetchToken(string code)
        {
            using (var client = new HttpClient())
            {
                client.Timeout = new TimeSpan(0, 0, 60);
                client.BaseAddress = new Uri(_lineNotifyConfig.TokenUrl);

                var content = new FormUrlEncodedContent(new[]
                {
                    new KeyValuePair<string, string>("grant_type", "authorization_code"),
                    new KeyValuePair<string, string>("code", code),
                    new KeyValuePair<string, string>("redirect_uri", _lineNotifyConfig.CallbackUrl),
                    new KeyValuePair<string, string>("client_id", _lineNotifyConfig.ClientId),
                    new KeyValuePair<string, string>("client_secret", _lineNotifyConfig.ClientSecret)
                });
                var response = await client.PostAsync("", content);
                var data = await response.Content.ReadAsStringAsync();

                var token = JsonConvert.DeserializeObject<JObject>(data)["access_token"].ToString();
                
                #region 新增到 TokenList
                string strNotifyTokenList = System.IO.File.ReadAllText("NotifyTokenList.json"); // 讀檔
                JObject jObjTokenList = JObject.Parse(strNotifyTokenList); // 轉成 JObj
                JArray jArrTokenList = (JArray)jObjTokenList["LineNotifyToken"]; // 取 LineNotifyToken 區塊
                LineNotifyToken userToken = new LineNotifyToken() { Token = token }; // 產生 Token 物件
                string strToken = JsonConvert.SerializeObject(userToken); // 序列化 Token 物件
                JObject jObjToken = JObject.Parse(strToken); // 轉成 JObject
                jArrTokenList.Add(jObjToken); // 新增 Token
                string strConvert = Convert.ToString(jObjTokenList); // 轉回 string
                System.IO.File.WriteAllText("NotifyTokenList.json", strConvert); // 存檔
                #endregion

                // 發測試通知
                isRock.LineNotify.Utility.SendNotify(token, DateTime.Now.ToString() + "這是測試通知。");

                return token;
            }
        }
    }
}

LineBot_Order_Core_Web/Controllers/HomeController.cs
using LineBot_Order_Core_Web.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Newtonsoft.Json.Linq;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace LineBot_Order_Core_Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly LineNotifyConfig _lineNotifyConfig;

        public HomeController(ILogger<HomeController> logger, LineNotifyConfig lineNotifyConfig)
        {
            _logger = logger;
            _lineNotifyConfig = lineNotifyConfig;
        }

        public IActionResult Index()
        {           
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
        
        public IActionResult NotifyTokenSuccess()
        {
            return View();
        }
        public IActionResult OrderList()
        {
            return View(Order.lisOrder);
        }
        public IActionResult UserList()
        {
            #region 讀取 UserList.json 到 lisUser
            string strUserList = System.IO.File.ReadAllText("UserList.json");
            JObject objUserList = JObject.Parse(strUserList);
            JArray arrayUserList = (JArray)objUserList["User"];
            IList<User> lisUser = arrayUserList.ToObject<List<User>>();
            #endregion

            return View(lisUser);
        }
    }
}

LineBot_Order_Core_Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<style>
    table,
    td {
        border: 1px solid #333;
    }

    thead,
    tfoot {
        background-color: #333;
        color: #fff;
    }
</style>

<div class="text-center">
    <h1 class="display-4">LineBot 點餐機器人(測試版)</h1>
    <br />
    <div class="text-xl-left">
        <p>大家好，我是新人 Leo Shen，因為看 Vincent 每天幫大家訂午餐很新辛苦，寫了個測試的 LineBot 點餐系統試試看簡化他的訂餐作業。</p>
        <p>新手上路都是查網路的資訊做的，可能寫得沒有很好，有測到 Bug 可以跟我說，能力範圍之內我會盡量修改。</p>
        <p>我的信箱：leoshen@airiti.com</p>
        <a href="https://github.com/leofcshen/LineBot_Order_Core_Web" target="_blank">源碼</a>
    </div>
    <br />

    <div>
        <h1>使用說明</h1>
        請用 Line 加入 bot ID：@@814xgjyd
        也可用 QR Code：<img src="https://qr-official.line.me/sid/L/814xgjyd.png" width="150" />
    </div>

    <div>
        <h1>指令說明</h1>
        <br />
        <h4>下列指令會有相對應的後台操作及機器人回覆，回覆內容只有你自己會看到。</h4>
        <br />
        <table>
            <thead>
                <tr>
                    <th colspan="3">未註冊 (請先註冊才能使用後續操作)</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>功能</td>
                    <td>指令</td>
                    <td>備註</td>
                </tr>
                <tr>
                    <td>註冊</td>
                    <td>!register 工號 姓名</td>
                    <td>範例：  !register 11084 Leo_Shen</td>
                </tr>
            </tbody>
        </table>
        <br />
        <table>
            <thead>
                <tr>
                    <th colspan="3">已註冊</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>功能</td>
                    <td>指令</td>
                    <td>備註</td>
                </tr>

                <tr>
                    <td>查詢使用者資料</td>
                    <td>!info</td>
                    <td></td>
                </tr>

                <tr>
                    <td>查詢菜單</td>
                    <td>!menu</td>
                    <td></td>
                </tr>

                <tr>
                    <td>訂餐</td>
                    <td>!order 品項 飯類(1:白飯 2:紫米) 飯量(1:正常 2:減半)<br />點完可下 !list 確認訂單     
                    或在網站的訂餐清單查看，如有異常請通知管理員。
                    </td>
                    <td>範例： !order 2 1 1</td>
                </tr>

                <tr>
                    <td>查詢訂餐清單</td>
                    <td>!list</td>
                    <td></td>
                </tr>

                <tr>
                    <td>刪除訂餐</td>
                    <td>!delete</td>
                    <td></td>
                </tr>
            </tbody>
        </table>
        <br />
        <table>
            <thead>
                <tr>
                    <th colspan="3">管理員指令</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>功能</td>
                    <td>指令</td>
                    <td>備註</td>
                </tr>

                <tr>
                    <td>發送通知</td>
                    <td>!notify 通知內容</td>
                    <td></td>
                </tr>

                <tr>
                    <td>開團</td>
                    <td>!start</td>
                    <td></td>
                </tr>

                <tr>
                    <td>結單</td>
                    <td>!end</td>
                    <td></td>
                </tr>

                <tr>
                    <td>查詢開團狀態</td>
                    <td>!isStart</td>
                    <td></td>
                </tr>

                <tr>
                    <td>修改開團狀態</td>
                    <td>!isStart 參數</td>
                    <td>參數：treu/false</td>
                </tr>

                <tr>
                    <td>停用帳號</td>
                    <td>!disable 工號</td>
                    <td></td>
                </tr>

                <tr>
                    <td>啟用帳號</td>
                    <td>!enable 工號</td>
                    <td></td>
                </tr>

                <tr>
                    <td>修改權限</td>
                    <td>!role 工號 role</td>
                    <td></td>
                </tr>


            </tbody>
        </table>
    </div>
    <br />
    <div style="float:left">
        <br /><br />
        <h1>連動 Line Notify</h1>
        <p>請按下列按扭進行 Line Notify 通知連動，有連動才能收到開團通知。</p>
        <button onclick="location.href='@Url.Action("GetAuthorize", "Authorize")'">按我連動 LineNotify</button>
        <p>點選後看到如右頁面，點選 "透過一對一聊天接收通知" > 同意並連動。</p>
    </div>
    <div>
        <img src="~/photo/AddNtifyExample.png" style="width:30%"/>
    </div>

    <div>
        <h1>訂餐流程簡述</h1>
        <p>管理員開團 > 對 Notify 發送通知及菜單 > 使用者可開始對 Line Bot !order 訂餐 > 管理員結單 > 對 Notify 發送通知及訂餐清單</p>
    </div>
    
    
</div>

LineBot_Order_Core_Web/Views/Home/NotifyTokenSuccess.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<div>
    <img src="~/photo/Success.jpg" style="display:block; margin:auto;"/>
</div>

<script>
    window.alert("通知機器人連動成功\n已可透過 Line Notify 接收通知。\n待會會收到一個測試通知。\n3秒後自動跳轉回首頁")
    setTimeout("javascript:location.href='/Home/Index'", 3000);
</script>

LineBot_Order_Core_Web/Views/Home/OrderList.cshtml
@model List<LineBot_Order_Core_Web.Models.Order>
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<style>
    table,
    td {
        border: 1px solid #333;
    }

    thead,
    tfoot {
        background-color: #333;
        color: #fff;
    }
</style>
<h1>訂餐清單</h1>
@if (Model.Count != 0)
{    
    <table>
        <thead>
            <tr>
                <th>訂餐人</th>
                <th>餐點</th>
                <th>飯類</th>
                <th>飯量</th>
                <th>價格</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>@item.name</td>
                    <td>@item.meal</td>
                    <td>@item.rice</td>
                    <td>@item.riceQuantity</td>                    
                    <td>@item.Price</td>
                </tr>
            }
        </tbody>
    </table>
}
else
{
    <p>目前無人訂餐</p>
}

LineBot_Order_Core_Web/Views/Home/UserList.cshtml
@model List<LineBot_Order_Core_Web.Models.User>
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<style>
    table,
    td {
        border: 1px solid #333;
    }

    thead,
    tfoot {
        background-color: #333;
        color: #fff;
    }
</style>
<h1>用戶清單</h1>



<table>
    <thead>
        <tr>
            <th>工號</th>
            <th>姓名</th>
            <th>權限</th>
        </tr>
    </thead>    
    <tbody>
        @foreach (var item in Model) {
            <tr>
                <td>@item.EmployeeID</td>
                <td>@item.UserName</td>
                <td>@item.Role</td>
            </tr>
            }
    </tbody>
</table>